import type { Metadata } from "next";
import { Tinos } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Provider from "./Provider";
import { Toaster } from "sonner";

const tinos = Tinos({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tinos.className}>
        <Provider>
          <Navbar />
          {children}
          <Footer />
          <Toaster richColors />
        </Provider>
      </body>
    </html>
  );
}
